
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: job1
  job2:
    name: job2
    needs: job1
  job3:
    name: job3
    needs: [job1, job2]
#  build:
#    name:
