
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: job1
  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2
  job3:
    name: job3
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: job3
#  build:
#    name:
